
services:
  alpine-nginx-nodejs-websocketd-hl:
    build: .
    image: hackinglab/alpine-nginx-nodejs-websocketd-hl:3.2
    environment:
    - AUTHOR=e1
    - HL_USER_USERNAME=hacker
    - HL_USER_PASSWORD=compass
    - NodeJSName=Demo-WebSocketd
    - NodeJSBase=http://localhost/static
    - NodeJSWebsocketUrl=ws://localhost/api
    ports:
      - 80:80
    volumes:
      - ./scripts:/opt/scripts


